name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [stable, beta, nightly, msrv]
        include:
          - build: stable
            rust: stable
          - build: beta
            rust: beta
          - build: nightly
            rust: nightly
          - build: msrv
            rust: 1.40.0
    steps:
      - uses: actions/checkout@master
      - name: Install Rust (rustup)
        run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
        shell: bash
      - run: cargo build
      - run: cargo test

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update nightly && rustup default nightly && rustup component add rustfmt
      - run: cargo fmt -- --check
